---
- name: "North Star | Leaf Playbook"
  hosts: arista_leaf_switches

  tasks:
    - name: "Configure Hostname"
      arista.eos.eos_system:
        hostname: "{{ inventory_hostname }}"

    - name: "Set Basic Configuration, MSTP, and SSH"
      arista.eos.eos_config:
        lines:
          - banner login "UNAUTHORIZED ACCESS PROHIBITED"
          - "username leafadmin secret leafpass"
          - "enable password leafpassenable"
          - "spanning-tree mode mstp"
          - "spanning-tree priority 4096"
          - "idle-timeout 15"
        parents: "management ssh"

    - name: "Configure VLANs"
      arista.eos.eos_vlans:
        config:
          - vlan_id: "{{ item.id }}"
            name: "{{ item.name }}"
        state: merged
      loop: "{{ north_star_vlans }}"

    - name: "Configure VLAN Descriptions"
      arista.eos.eos_interfaces:
        config:
          - name: "VLAN{{ item.id }}"
            description: "{{ item.description }}"
        state: merged
      loop: "{{ north_star_vlans }}"

    - name: "Configure Physical Interfaces"
      arista.eos.eos_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "Uplink to {{ item.peer }}"
            enabled: true # For non-Arista devices
        state: merged
      loop: "{{ leaf_interfaces }}"

    - name: "Configure Port Channels on Physical Interfaces"
      arista.eos.eos_lag_interfaces:
        config:
          - name: "Port-Channel{{ item.channel }}"
            members:
              - member: "{{ item.name }}"
                mode: active
        state: merged
      loop: "{{ leaf_interfaces }}"

    - name: "Configure Port-Channels to Spines"
      arista.eos.eos_l2_interfaces:
        config:
          - name: "Port-Channel{{ item.channel }}"
            mode: trunk
            trunk:
              trunk_allowed_vlans: "{{ trunk_vlans }}"
        state: merged
      loop: "{{ leaf_interfaces }}"

    - name: "Save Configuration"
      arista.eos.eos_config:
        save_when: modified
