---
- name: "North Star | Leaf Playbook"
  hosts: arista_leaf_switches

  tasks:
    - name: "Configure Hostname"
      arista.eos.eos_system:
        hostname: "{{ inventory_hostname }}"

    - name: "Set Basic Configuration"
      arista.eos.eos_config:
        lines:
          - banner login "UNAUTHORIZED ACCESS PROHIBITED"
          - "enable password leafpassenable"

    - name: "Configure SSH Timeout"
      arista.eos.eos_config:
        lines:
          - "idle-timeout 15"
        parents: "management ssh"

    - name: "Configure VLANs"
      arista.eos.eos_vlans:
        config:
          - vlan_id: "{{ item.id }}"
            name: "{{ item.name }}"
        state: merged
      loop: "{{ north_star_vlans }}"

    - name: "Configure Physical Interfaces"
      arista.eos.eos_config:
        lines:
          - "description Uplink to {{ item.peer }}"
          - "switchport mode trunk"
          - "switchport trunk allowed vlan {{ trunk_vlans }}"
          - "channel-group {{ item.channel }} mode active"
        parents: "interface {{ item.name }}"
      loop: "{{ spine_interfaces }}"

    - name: "Save Configuration"
      arista.eos.eos_config:
        save_when: modified
