---
all:
  children:
    arista_switches:
      children:
         arista_leaf_switches:
           hosts:
             karlo-cn-leaf-01:
               ansible_host: 10.0.10.106
             karlo-cn-leaf-02:
               ansible_host: 10.0.10.107
         arista_spine_switches:
           hosts:
             karlo-cn-spine-01:
               ansible_host: 10.0.10.104
             karlo-cn-spine-02:
               ansible_host: 10.0.10.105

    vyos_routers:
      hosts:
        karlo-cn-rtr-01:
          ansible_host: 10.0.10.1
        karlo-cn-rtr-02:
          ansible_host: 10.0.10.2
